### ISSUE TITLE
IP请求次数限制

### ISSUE THREAD

**Issue by vanpersiexp** [youngytj/t66y_InvitationCode#2]
怎么处理IP请求次数限制的问题？

**Comment by tianjyan** [comment]
请问遇到什么具体的问题了吗？

**Comment by vanpersiexp** [comment]
一般请求次数过多，开始限制ip访问，挂一个vpn换ip后才可以正常访问，想请教一下这种情况怎么能实现自动变更呢。
免费的ip代理基本上都不太能用。

**Comment by tianjyan** [comment]
这个问题和这个repo有关吗
